name = "cf-postal-worker"
compatibility_date = "2023-01-01"
send_email = [
    {type = "send_email", name = "SEB"}
]

[vars]
SENDER_ADDRESS = "info@southpasadenawebdesign.com"
SENDER_NAME = "southpasadenawebdesign"
RECIPIENT_ADDRESS = "damiankrzyz@gmail.com"
ALLOWED_ORIGINS = "*"
